using System.Collections.Generic;
using CurrencyExchanger.Dtos;
using CurrencyExchanger.Entities;

namespace CurrencyExchanger 
{
    public static class Extentions 
    {
        public static ExchangeDto AsDto(this Exchange exchange ) 
        {
            return new ExchangeDto 
            {
                Date = exchange.Date,
                From = exchange.Currency1,
                To = exchange.Currency2,
                Amount = exchange.Amount,
                ExchangeRate = exchange.ExchangeRate,
                ConvertResult = exchange.ConvertResult
            };
        }

        public static RateDto AsDto(this Rate rate ) 
        {
            return new RateDto 
            {
                Currency = rate.Currency,
                EuroRate = rate.EuroRate,
            };
        }

        public static List<Rate> AsList(this Rates rates) {
            return new List<Rate> 
            {
                new Rate { Currency = "AED", EuroRate = rates.AED },
                new Rate { Currency = "AFN", EuroRate = rates.AFN },
                new Rate { Currency = "ALL", EuroRate = rates.ALL },
                new Rate { Currency = "AMD", EuroRate = rates.AMD },
                new Rate { Currency = "ANG", EuroRate = rates.ANG },
                new Rate { Currency = "AOA", EuroRate = rates.AOA },
                new Rate { Currency = "ARS", EuroRate = rates.ARS },
                new Rate { Currency = "AUD", EuroRate = rates.AUD },
                new Rate { Currency = "AUD", EuroRate = rates.AUD },
                new Rate { Currency = "AWG", EuroRate = rates.AWG },
                new Rate { Currency = "AZN", EuroRate = rates.AZN },
                new Rate { Currency = "BAM", EuroRate = rates.BAM },
                new Rate { Currency = "BBD", EuroRate = rates.BBD },
                new Rate { Currency = "BDT", EuroRate = rates.BDT },
                new Rate { Currency = "BGN", EuroRate = rates.BGN },
                new Rate { Currency = "BHD", EuroRate = rates.BHD },
                new Rate { Currency = "BIF", EuroRate = rates.BIF },
                new Rate { Currency = "BMD", EuroRate = rates.BMD },
                new Rate { Currency = "BND", EuroRate = rates.BND },
                new Rate { Currency = "BOB", EuroRate = rates.BOB },
                new Rate { Currency = "BRL", EuroRate = rates.BRL },
                new Rate { Currency = "BSD", EuroRate = rates.BSD },
                new Rate { Currency = "BTC", EuroRate = rates.BTC },
                new Rate { Currency = "BTN", EuroRate = rates.BTN },
                new Rate { Currency = "BWP", EuroRate = rates.BWP },
                new Rate { Currency = "BYN", EuroRate = rates.BYN },
                new Rate { Currency = "BYR", EuroRate = rates.BYR },
                new Rate { Currency = "BZD", EuroRate = rates.BZD },
                new Rate { Currency = "CAD", EuroRate = rates.CAD },
                new Rate { Currency = "CDF", EuroRate = rates.CDF },
                new Rate { Currency = "CHF", EuroRate = rates.CHF },
                new Rate { Currency = "CLF", EuroRate = rates.CLF },
                new Rate { Currency = "CLP", EuroRate = rates.CLP },
                new Rate { Currency = "CNY", EuroRate = rates.CNY },
                new Rate { Currency = "COP", EuroRate = rates.COP },
                new Rate { Currency = "CRC", EuroRate = rates.CRC },
                new Rate { Currency = "CUC", EuroRate = rates.CUC },
                new Rate { Currency = "CUP", EuroRate = rates.CUP },
                new Rate { Currency = "CVE", EuroRate = rates.CVE },
                new Rate { Currency = "CVE", EuroRate = rates.CVE },
                new Rate { Currency = "CZK", EuroRate = rates.CZK },
                new Rate { Currency = "DJF", EuroRate = rates.DJF },
                new Rate { Currency = "DKK", EuroRate = rates.DKK },
                new Rate { Currency = "DOP", EuroRate = rates.DOP },
                new Rate { Currency = "DZD", EuroRate = rates.DZD },
                new Rate { Currency = "EGP", EuroRate = rates.EGP },
                new Rate { Currency = "ERN", EuroRate = rates.ERN },
                new Rate { Currency = "ETB", EuroRate = rates.ETB },
                new Rate { Currency = "EUR", EuroRate = rates.EUR },
                new Rate { Currency = "FJD", EuroRate = rates.FJD },
                new Rate { Currency = "FKP", EuroRate = rates.FKP },
                new Rate { Currency = "GBP", EuroRate = rates.GBP },
                new Rate { Currency = "GEL", EuroRate = rates.GEL },
                new Rate { Currency = "GGP", EuroRate = rates.GGP },
                new Rate { Currency = "GHS", EuroRate = rates.GHS },
                new Rate { Currency = "GIP", EuroRate = rates.GIP },
                new Rate { Currency = "GMD", EuroRate = rates.GMD },
                new Rate { Currency = "GNF", EuroRate = rates.GNF },
                new Rate { Currency = "GNF", EuroRate = rates.GNF },
                new Rate { Currency = "GTQ", EuroRate = rates.GTQ },
                new Rate { Currency = "GYD", EuroRate = rates.GYD },
                new Rate { Currency = "HKD", EuroRate = rates.HKD },
                new Rate { Currency = "HNL", EuroRate = rates.HNL },
                new Rate { Currency = "HRK", EuroRate = rates.HRK },
                new Rate { Currency = "HTG", EuroRate = rates.HTG },
                new Rate { Currency = "HUF", EuroRate = rates.HUF },
                new Rate { Currency = "IDR", EuroRate = rates.IDR },
                new Rate { Currency = "ILS", EuroRate = rates.ILS },
                new Rate { Currency = "IMP", EuroRate = rates.IMP },
                new Rate { Currency = "INR", EuroRate = rates.INR },
                new Rate { Currency = "IQD", EuroRate = rates.IQD },
                new Rate { Currency = "IRR", EuroRate = rates.IRR },
                new Rate { Currency = "ISK", EuroRate = rates.ISK },
                new Rate { Currency = "JEP", EuroRate = rates.JEP },
                new Rate { Currency = "JMD", EuroRate = rates.JMD },
                new Rate { Currency = "JOD", EuroRate = rates.JOD },
                new Rate { Currency = "JPY", EuroRate = rates.JPY },
                new Rate { Currency = "KES", EuroRate = rates.KES },
                new Rate { Currency = "KGS", EuroRate = rates.KGS },
                new Rate { Currency = "KHR", EuroRate = rates.KHR },
                new Rate { Currency = "KMF", EuroRate = rates.KMF },
                new Rate { Currency = "KPW", EuroRate = rates.KPW },
                new Rate { Currency = "KRW", EuroRate = rates.KRW },
                new Rate { Currency = "KWD", EuroRate = rates.KWD },
                new Rate { Currency = "KYD", EuroRate = rates.KYD },
                new Rate { Currency = "KZT", EuroRate = rates.KZT },
                new Rate { Currency = "LAK", EuroRate = rates.LAK },
                new Rate { Currency = "LBP", EuroRate = rates.LBP },
                new Rate { Currency = "LKR", EuroRate = rates.LKR },
                new Rate { Currency = "LRD", EuroRate = rates.LRD },
                new Rate { Currency = "LSL", EuroRate = rates.LSL },
                new Rate { Currency = "LTL", EuroRate = rates.LTL },
                new Rate { Currency = "LVL", EuroRate = rates.LVL },
                new Rate { Currency = "LYD", EuroRate = rates.LYD },
                new Rate { Currency = "MAD", EuroRate = rates.MAD },
                new Rate { Currency = "MDL", EuroRate = rates.MDL },
                new Rate { Currency = "MGA", EuroRate = rates.MGA },
                new Rate { Currency = "MKD", EuroRate = rates.MKD },
                new Rate { Currency = "MMK", EuroRate = rates.MMK },
                new Rate { Currency = "MNT", EuroRate = rates.MNT },
                new Rate { Currency = "MOP", EuroRate = rates.MOP },
                new Rate { Currency = "MRO", EuroRate = rates.MRO },
                new Rate { Currency = "MUR", EuroRate = rates.MUR },
                new Rate { Currency = "MVR", EuroRate = rates.MVR },
                new Rate { Currency = "MWK", EuroRate = rates.MWK },
                new Rate { Currency = "MXN", EuroRate = rates.MXN },
                new Rate { Currency = "MYR", EuroRate = rates.MYR },
                new Rate { Currency = "MZN", EuroRate = rates.MZN },
                new Rate { Currency = "NAD", EuroRate = rates.NAD },
                new Rate { Currency = "NGN", EuroRate = rates.NGN },
                new Rate { Currency = "NIO", EuroRate = rates.NIO },
                new Rate { Currency = "NOK", EuroRate = rates.NOK },
                new Rate { Currency = "NPR", EuroRate = rates.NPR },
                new Rate { Currency = "NZD", EuroRate = rates.NZD },
                new Rate { Currency = "OMR", EuroRate = rates.OMR },
                new Rate { Currency = "PAB", EuroRate = rates.PAB },
                new Rate { Currency = "PEN", EuroRate = rates.PEN },
                new Rate { Currency = "PGK", EuroRate = rates.PGK },
                new Rate { Currency = "PHP", EuroRate = rates.PHP },
                new Rate { Currency = "PKR", EuroRate = rates.PKR },
                new Rate { Currency = "PLN", EuroRate = rates.PLN },
                new Rate { Currency = "PYG", EuroRate = rates.PYG },
                new Rate { Currency = "QAR", EuroRate = rates.QAR },
                new Rate { Currency = "RON", EuroRate = rates.RON },
                new Rate { Currency = "RSD", EuroRate = rates.RSD },
                new Rate { Currency = "RUB", EuroRate = rates.RUB },
                new Rate { Currency = "RWF", EuroRate = rates.RWF },
                new Rate { Currency = "SAR", EuroRate = rates.SAR },
                new Rate { Currency = "SBD", EuroRate = rates.SBD },
                new Rate { Currency = "SCR", EuroRate = rates.SCR },
                new Rate { Currency = "SDG", EuroRate = rates.SDG },
                new Rate { Currency = "SEK", EuroRate = rates.SEK },
                new Rate { Currency = "SGD", EuroRate = rates.SGD },
                new Rate { Currency = "SHP", EuroRate = rates.SHP },
                new Rate { Currency = "SLL", EuroRate = rates.SLL },
                new Rate { Currency = "SOS", EuroRate = rates.SOS },
                new Rate { Currency = "SRD", EuroRate = rates.SRD },
                new Rate { Currency = "STD", EuroRate = rates.STD },
                new Rate { Currency = "SVC", EuroRate = rates.SVC },
                new Rate { Currency = "SYP", EuroRate = rates.SYP },
                new Rate { Currency = "SZL", EuroRate = rates.SZL },
                new Rate { Currency = "THB", EuroRate = rates.THB },
                new Rate { Currency = "TJS", EuroRate = rates.TJS },
                new Rate { Currency = "TMT", EuroRate = rates.TMT },
                new Rate { Currency = "TND", EuroRate = rates.TND },
                new Rate { Currency = "TOP", EuroRate = rates.TOP },
                new Rate { Currency = "TRY", EuroRate = rates.TRY },
                new Rate { Currency = "TTD", EuroRate = rates.TTD },
                new Rate { Currency = "TWD", EuroRate = rates.TWD },
                new Rate { Currency = "TZS", EuroRate = rates.TZS },
                new Rate { Currency = "UAH", EuroRate = rates.UAH },
                new Rate { Currency = "UGX", EuroRate = rates.UGX },
                new Rate { Currency = "USD", EuroRate = rates.USD },
                new Rate { Currency = "UYU", EuroRate = rates.UYU },
                new Rate { Currency = "UZS", EuroRate = rates.UZS },
                new Rate { Currency = "VEF", EuroRate = rates.VEF },
                new Rate { Currency = "VND", EuroRate = rates.VND },
                new Rate { Currency = "VUV", EuroRate = rates.VUV },
                new Rate { Currency = "WST", EuroRate = rates.WST },
                new Rate { Currency = "XAF", EuroRate = rates.XAF },
                new Rate { Currency = "XAG", EuroRate = rates.XAG },
                new Rate { Currency = "XAU", EuroRate = rates.XAU },
                new Rate { Currency = "XCD", EuroRate = rates.XCD },
                new Rate { Currency = "XDR", EuroRate = rates.XDR },
                new Rate { Currency = "XOF", EuroRate = rates.XOF },
                new Rate { Currency = "XPF", EuroRate = rates.XPF },
                new Rate { Currency = "YER", EuroRate = rates.YER },
                new Rate { Currency = "ZAR", EuroRate = rates.ZAR },
                new Rate { Currency = "ZMK", EuroRate = rates.ZMK },
                new Rate { Currency = "ZMW", EuroRate = rates.ZMW },
                new Rate { Currency = "ZWL", EuroRate = rates.ZWL }             
            };
        }
    }
    
}